### ISSUE TITLE
Please add support for non English 

### ISSUE THREAD

**Issue by arpiaa** [noCaptchaAi/hCaptchaSolver.user.js#15]
Currently not solving if browser language is not English

<img width="1271" alt="Screenshot 2022-10-01 005853" src="https://user-images.githubusercontent.com/114644012/193343104-4e779d31-951a-452f-925d-8dbef38e13d2.png">

**Comment by DiegoSawyer** [comment]
what version are you using?
try using the new version and see if it helped you
[Click here to install](https://github.com/noCaptchaAi/hCaptchaSolver.user.js/raw/main/hCaptchaSolver.user.js)

**Comment by arpiaa** [comment]
Already using v1

> what version are you using? try using the new version and see if it helped you [Click here to install](https://github.com/noCaptchaAi/hCaptchaSolver.user.js/raw/main/hCaptchaSolver.user.js)

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/114644012/193345326-e6e77fc3-1d05-46da-913e-4a402168b057.png">
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/114644012/193345460-e2bf8a2e-d1ef-4bd1-b6c0-2fb3d7c2c2f7.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/114644012/193345492-37d2cb7e-526a-4b41-9d8f-90cbd3452727.png">

**Comment by DiegoSawyer** [comment]
we currently have a system that tries to bypass the language
but it doesn't work on all sites
we are still trying to find a solution for all sites

it can take time

for now you can use this extension until the solution is found
[Locale Switcher](https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc)

**Comment by arpiaa** [comment]
> we currently have a system that tries to bypass the language but it doesn't work on all sites we are still trying to find a solution for all sites
> 
> it can take time
> 
> for now you can use this extension until the solution is found [Locale Switcher](https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc)

Not working for my case.

Please check yourself https://bezkolejki.eu/suw3

**Comment by shimuldn** [comment]
We are planning to officially support all languages, so please hold on a little while longer.

**Comment by shimuldn** [comment]
Language support is now live.
Please check https://docs.nocaptchaai.com/Methods/solve for supported languages.

**Comment by arpiaa** [comment]
Perfect, Thanks
