### ISSUE TITLE
Not solving for proxy or slow internet

### ISSUE THREAD

**Issue by shimuldn** [noCaptchaAi/hCaptchaSolver.user.js#17]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/12117121/203233621-9dc8e18f-91c2-42aa-8be6-0a27dbc5110c.png">

**Comment by debpalash** [comment]
@v2 fixes proxy support https://github.com/noCaptchaAi/hCaptchaSolver.user.js/pull/20
